### ISSUE TITLE
四連桿模擬路徑繪圖錯誤

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/Pyslvs-PyQt5#2]
#  四連桿路徑繪圖錯誤

https://github.com/mdecourse/Pyslvs-PyQt5/blob/master/bugs_report/fourbar_bug1.pyslvs

**Comment by KmolYuan** [comment]
This logical error was fixed in https://github.com/KmolYuan/Pyslvs-PyQt5/commit/fdc2174cdc6fdd74cf8bc50636a0b5aa75fbf6aa.

**Comment by mdecourse** [comment]
先前繪圖錯誤已經修正, 但是修改機構點位置後存檔後, 無法正確設定 drive link, export 為 solvespace 檔案後, 則可順利進行模擬.

https://github.com/mdecourse/Pyslvs-PyQt5/blob/master/bugs_report/fourbar_bug2.pyslvs
